CONTAINER Tmwvisibility
{
	NAME Tmwvisibility;
    INCLUDE Texpression;

    GROUP ID_TAGPROPERTIES
	{
		DEFAULT 1; COLUMNS 1;
		
		GROUP MWVISIBILITY_ACTIVE_VIS
		{
			DEFAULT 1; COLUMNS 1;
			GROUP
			{
				LAYOUTGROUP; DEFAULT 1; COLUMNS 2;
				GROUP
				{
					BOOL MWVISIBILITY_VIEWPORT {}
					REAL MWVISIBILITY_SCALE_VIS_OFF {MIN 0.0; MAX 1.0; STEP 0.01;}
				}
				GROUP
				{
					BOOL MWVISIBILITY_RENDER {}
				}
			}
			/*
			LONG MWVISIBILITY_VISON_STATE
			{
				CUSTOMGUI QUICKTABRADIO;
				CYCLE
				{
					MWVISIBILITY_VISON_DEFAULT;
					MWVISIBILITY_VISON_ON;
				}
				ANIM OFF;
				
			}
			*/
		}

		GROUP MWVISIBILITY_VISGROUP
		{
			DEFAULT 1;
			COLUMNS 1;
			GROUP
			{
				LAYOUTGROUP; DEFAULT 1; COLUMNS 2;
				GROUP
				{	
					BUTTON MWVISIBILITY_VISFRAME_ADD {}
				}
				GROUP
				{
					BUTTON MWVISIBILITY_VISFRAME_DEL {}
				}
			}
/*			
			BASETIME MWVISIBILITY_VISFRAME { ANIM OFF; }
			LONG MWVISIBILITY_VIS_QUICKTAB
			{
				CUSTOMGUI QUICKTABRADIO;
				CYCLE
				{
					MWVISIBILITY_VIS_DEFAULT;
					MWVISIBILITY_VIS_ON;
					MWVISIBILITY_VIS_OFF;
				}
				ANIM OFF;
				
			}
*/
		}
		GROUP
		{
			BUTTON MWVISIBILITY_BAKEKEYFRAME {}
		}
	}
}
